# Config version
version: 0.3.0

# HTML Head settings
html:
  title: Fede Rey

# Main container settings
main:
  title: Fede Rey

# Blocks list
blocks:
  - title: Instagram
    icon: instagram
    url: https://instagram.com/federey22

  - title: Twitter
    icon: twitter
    url: https://twitter.com/Fede_R22

  - title: Sitio Web
    icon: url
    url: https://www.latone.com.ar/
